### ISSUE TITLE
How to define other atlas? like the Desikan-Killiany 308(DK-308),HCP-360?

### ISSUE THREAD

**Issue by linghaowind** [ggseg/python-ggseg#2]
Hello authors, I want to use python-ggseg to draw the result graph of my paper, but the atlas I use is not one of the three atlases you provided, could you kindly tell me how to make other atlases documents, such as DK-308, HCP-360. Thank you so much!

**Comment by xgrg** [comment]
Thank you @linghaowind for opening this issue. So far only three atlases are provided, which consist in "manual conversions" from the original R package. With @Athanasiamo, we have planned to improve the R to Python atlas translation, possibly with some procedure to build new ones or fix specific areas.

For the moment you may have a look at [this folder](https://github.com/ggseg/python-ggseg/tree/main/ggseg/data) where atlases and their regions are defined. Each file is a text file with a geometric description of the region it is named after. This description is given as a [path](https://www.w3schools.com/graphics/svg_path.asp) as in the SVG format. Depending on the amount of effort you are ready to put in this, you could get your own atlas by writing these paths/descriptions for all the regions.
The final step is writing the Python function that will get these files and draw the regions, which may reuse any of the three existing ones (DK, JHU, aseg) as a template.

This is not much but I hope this helps. If you do not have any further question, I will close the issue. Thanks again.

**Comment by linghaowind** [comment]
Thank you very much for your answer. I have no further questions.
