### ISSUE TITLE
new atlases

### ISSUE THREAD

**Issue by teanijarv** [ggseg/python-ggseg#8]
Hi! I already saw one closed issue about adding new atlases, but I just wanted to ask, if you could elaborate on how you generated these svg files for all DK ROIs? For example, Do you still have the script for creating this and could share this?

**Comment by xgrg** [comment]
Hi @teanijarv,
Quick answer as I unfortunately left the field years ago and have no more time to maintain this.
The closed issue you are mentioning already describes how the path/SVG files were generated for all the DK ROIs.
These were manual conversions from the representations provided by the R package. There is no automatic script. If you need a new atlas, you will have to provide (draw?) the SVG representations of the corresponding ROIs. Some tools (eg. Inkscape) can convert bitmaps to vector representations from which you can take the paths to feed `python-ggseg` with.
Does it help?

**Comment by teanijarv** [comment]
@xgrg Thanks for the quick response! 
Okay, seems like I have to put some time into drawing then; I was hoping that there is some better option. Currently I just converted the polygons from ggseg atlases and got a working solution, but it just never looked good enough, whereas your package is actually visually pleasing, but now I know that I need to do some hard manual labor for that. Thanks! 👍
